/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.fabrica;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Detallesorden;
import modelo.Ordenes;
import modelo.Productos;
import persistencia.DetallesordenJpaController;
import persistencia.OrdenesJpaController;
import persistencia.ProductosJpaController;
//import vista.fabrica.fabrica_pedidos;

/**
 *
 * @author Kings
 */
public class fabrica_pedidos_detalles extends javax.swing.JFrame {
    DetallesordenJpaController cDetalles = new DetallesordenJpaController();
    OrdenesJpaController cOrdenes = new OrdenesJpaController();
    ProductosJpaController cProductos = new ProductosJpaController();
    Detallesorden dEdit;
    /**
     * Creates new form fabrica_pedidos_detalles
     */
    public fabrica_pedidos_detalles() {
        initComponents();
        CrearModelo();
        Cargar_Informacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    DefaultTableModel modelo;
    private void CrearModelo() {
        try {
            modelo = (new DefaultTableModel(
                    null, new String[]{
                        "Producto", "Cantidad", "Color"}) {
                Class[] types = new Class[]{
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class
                };
                boolean[] canEdit = new boolean[]{
                    false, false, false
                };

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return canEdit[colIndex];
                }
            });
            tabla.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error");
            System.out.println("Problema con el modelo de tabla");
        }
    }
    
    private void Cargar_Informacion(){
            Object o[]=null;
            List<Ordenes> listO = cOrdenes.findOrdenesEntities();
            List<Detallesorden> listP = cDetalles.findDetallesordenEntities();
            int contadorr = 0;
            for (int i=0; i< listP.size(); i++){
               // System.out.println(fabrica_pedidos.oEdit);
             //   Ordenes ord = cOrdenes.findOrdenes(i);
              //  System.out.println(fabrica_pedidos.oEdit);
               // System.out.println(cOrdenes.findOrdenes(i));
               Ordenes numero = listP.get(i).getOrdCodigo();
               int numeroo = numero.getOrdCodigo();
               if(fabrica_pedidos.nume == numeroo){
                   Productos prod = listP.get(i).getProdCodigo();
                   
                  // System.out.println( prod.getProdNombre() +", Cantidad: "+ listP.get(i).getDetCantidad() +", Color: "+listP.get(i).getDetDescripcion() + "     " + i);
                    modelo.addRow(o);
                    modelo.setValueAt(prod.getProdNombre(), contadorr, 0);
                  //  modelo.setValueAt(Nombre, i, 0);
                    modelo.setValueAt(listP.get(i).getDetCantidad(), contadorr, 1);
                    modelo.setValueAt(listP.get(i).getDetDescripcion(), contadorr, 2);
                    contadorr++;
               }
               
            //    if(fabrica_pedidos.oEdit == cOrdenes.findOrdenes(i)){
              //      System.out.println("XXXXXXXXXXXXXXXXXXXXX"); 
              //  }else {System.out.println("No");}
             //   modelo.addRow(o);
            //    modelo.setValueAt(listP.get(i).getDetCantidad(), i, 0);
             //   modelo.setValueAt(listP.get(i).getDetDescripcion(), i, 1);
              //  if(fabrica_pedidos.codigoOrd == listP.get(i).getOrdCodigo().getOrdCodigo()){
                //    System.out.println("dkcmksmcskmcskd");
                    //String Nombre = cProductos.findProductos(cod).getProdNombre();
 
              //      modelo.addRow(o);
               //     modelo.setValueAt("dcdcd", i, 0);
                    //modelo.setValueAt(Nombre, i, 0);
                   // modelo.setValueAt(listP.get(i).getDetCantidad(), i, 1);
                 //   modelo.setValueAt(listP.get(i).getDetDescripcion(), i, 2);
                }
                                               
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fabrica_pedidos_detalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fabrica_pedidos_detalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fabrica_pedidos_detalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fabrica_pedidos_detalles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fabrica_pedidos_detalles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
