/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.admin;

import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Materiasprimas;
import modelo.Proveedores;
import persistencia.MateriasprimasJpaController;
import persistencia.ProveedoresJpaController;

/**
 *
 * @author Kings
 */
public class admin_gestionar_materiasPrimas extends javax.swing.JFrame {
    
    MateriasprimasJpaController cMateriasprimas = new MateriasprimasJpaController();
    ProveedoresJpaController cProveedores = new ProveedoresJpaController();
    Materiasprimas cEdit;
    
    /**
     * Creates new form admin_gestionar_materiasPrimas
     */
    public admin_gestionar_materiasPrimas() {
        initComponents();
        this.setMinimumSize(new Dimension(1400, 680));
        this.setLocationRelativeTo(null);
        CrearModelo();
        Cargar_Informacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCantidad = new javax.swing.JTextField();
        bSeleccionar = new javax.swing.JButton();
        txtPrecioC = new javax.swing.JTextField();
        txtNITP = new javax.swing.JTextField();
        bCancelar = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        bActualizar = new javax.swing.JButton();
        txtDescripcion = new javax.swing.JTextField();
        comboUnidad = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txtCantidad);
        txtCantidad.setBounds(280, 180, 180, 30);

        bSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bSeleccionar.png"))); // NOI18N
        bSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(bSeleccionar);
        bSeleccionar.setBounds(260, 500, 200, 50);
        getContentPane().add(txtPrecioC);
        txtPrecioC.setBounds(278, 232, 180, 30);
        getContentPane().add(txtNITP);
        txtNITP.setBounds(278, 332, 180, 30);

        bCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bCancelar0.png"))); // NOI18N
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(bCancelar);
        bCancelar.setBounds(50, 570, 200, 50);

        bGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bGuardar.png"))); // NOI18N
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(bGuardar);
        bGuardar.setBounds(260, 570, 200, 50);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(500, 20, 880, 600);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(278, 82, 180, 30);

        bActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bActualizar.png"))); // NOI18N
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(bActualizar);
        bActualizar.setBounds(50, 500, 200, 50);

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescripcion);
        txtDescripcion.setBounds(278, 132, 180, 30);

        comboUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kg", "Gal" }));
        getContentPane().add(comboUnidad);
        comboUnidad.setBounds(278, 282, 180, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Gestionar_MateriasPrimas.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1400, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeleccionarActionPerformed
        txtNombre.setText(tabla.getValueAt(tabla.getSelectedRow(), 1).toString());
        txtDescripcion.setText(tabla.getValueAt(tabla.getSelectedRow(), 2).toString());
        comboUnidad.setSelectedItem(modelo.getValueAt(tabla.getSelectedRow(), 3).toString());
        txtCantidad.setText(tabla.getValueAt(tabla.getSelectedRow(), 4).toString());
        txtPrecioC.setText(tabla.getValueAt(tabla.getSelectedRow(), 5).toString());   
        txtNITP.setText(tabla.getValueAt(tabla.getSelectedRow(), 6).toString());

        cEdit = cMateriasprimas.findMateriasprimas((Integer) modelo.getValueAt(tabla.getSelectedRow(), 0));
    }//GEN-LAST:event_bSeleccionarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        admin_gestionar ventana = new admin_gestionar();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        try {
            Materiasprimas c = new Materiasprimas();

            c.setMatNombre(txtNombre.getText());
            c.setMatDescripcion(txtDescripcion.getText());
            c.setMatUnidadMedida((String) comboUnidad.getSelectedItem());
            c.setMatCatidad(Integer.parseInt(txtCantidad.getText()));
            c.setMatPrecioComprado(Integer.parseInt(txtPrecioC.getText()));
            Proveedores prov = new Proveedores();
            prov.proNIT = (txtNITP.getText());
            c.setProNIT(prov);

            cMateriasprimas.create(c);
            System.out.println("Los datos fueron guardados");

            CrearModelo();
            Cargar_Informacion();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("Problema el guardar datos");
        } 
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        try{
            cEdit.setMatNombre(txtNombre.getText());
            cEdit.setMatDescripcion(txtDescripcion.getText());
            cEdit.setMatCatidad(Integer.parseInt(txtCantidad.getText()));
            cEdit.setMatPrecioComprado(Integer.parseInt(txtPrecioC.getText()));
            cEdit.setProNIT(cProveedores.findProveedores(txtNITP.getText()));

            cMateriasprimas.edit(cEdit);
            System.out.println("Se actualizo");
            CrearModelo();
            Cargar_Informacion();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.toString() + "error");
            System.out.println("Error al actualizar");
        } 
    }//GEN-LAST:event_bActualizarActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    DefaultTableModel modelo;
    private void CrearModelo() {
        try {
            modelo = (new DefaultTableModel(
                    null, new String[]{
                        "Codigo", "Nombre", "Descripcion",
                        "Unidad", "Cantidad", "P. Comprado",
                        "Proveedor"}) {
                Class[] types = new Class[]{
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class
                };
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false
                };

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return canEdit[colIndex];
                }
            });
            tabla.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error");
            System.out.println("Problema con el modelo de tabla");
        }
    }
    
    
    private void Cargar_Informacion(){
        try{
            Object o[]=null;
            List<Materiasprimas> listP = cMateriasprimas.findMateriasprimasEntities();
            
            for (int i=0; i< listP.size(); i++){
                modelo.addRow(o);
                modelo.setValueAt(listP.get(i).getMatCodigo(), i, 0);
                modelo.setValueAt(listP.get(i).getMatNombre(), i, 1);
                modelo.setValueAt(listP.get(i).getMatDescripcion(), i, 2);
                modelo.setValueAt(listP.get(i).getMatUnidadMedida(), i, 3);
                modelo.setValueAt(listP.get(i).getMatCatidad(), i, 4);
                modelo.setValueAt(listP.get(i).getMatPrecioComprado(), i, 5);
                modelo.setValueAt(listP.get(i).getProNIT().getProNIT(), i, 6);
                
            }                                            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("problema al cargar datos");
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_gestionar_materiasPrimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_gestionar_materiasPrimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_gestionar_materiasPrimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_gestionar_materiasPrimas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_gestionar_materiasPrimas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bSeleccionar;
    private javax.swing.JComboBox<String> comboUnidad;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNITP;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecioC;
    // End of variables declaration//GEN-END:variables
}
