/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.admin;

import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Empleados;
import persistencia.EmpleadosJpaController;
import java.util.Date;

import java.text.DateFormat;

/**
 *
 * @author Kings
 */
public class admin_gestionar_empleados extends javax.swing.JFrame {
    
    EmpleadosJpaController cEmpleados = new EmpleadosJpaController();
    Empleados cEdit;
    
    
    java.util.Date fecha = new Date();
    String strDateFormat = "dd/MM/y";
    SimpleDateFormat objSDF = new SimpleDateFormat(strDateFormat);
    //System.out.println(objSDF.format(fecha));
    String fechaHoy = objSDF.format(fecha);
    
    /**
     * Creates new form admin_gestionar_empleados
     */
    public admin_gestionar_empleados() {
        initComponents();
        this.setMinimumSize(new Dimension(1400, 680));
        this.setLocationRelativeTo(null);
        CrearModelo();
        Cargar_Informacion();
    }
    
    public static String darFormato(Date date) {
        if(date == null){
            return null;
        }else {
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd/MM/yyyy");
            return simpleDateFormat.format(date).toUpperCase();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSeleccionar = new javax.swing.JButton();
        txtSalario = new javax.swing.JTextField();
        bCancelar = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtNombre = new javax.swing.JTextField();
        bActualizar = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        comboGenero = new javax.swing.JComboBox<>();
        comboCargo = new javax.swing.JComboBox<>();
        dateNacimiento = new com.toedter.calendar.JDateChooser();
        dateContratacion = new com.toedter.calendar.JDateChooser();
        dateDespido = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bSeleccionar.png"))); // NOI18N
        bSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(bSeleccionar);
        bSeleccionar.setBounds(50, 570, 200, 50);
        getContentPane().add(txtSalario);
        txtSalario.setBounds(220, 382, 210, 30);

        bCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bCancelar0.png"))); // NOI18N
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(bCancelar);
        bCancelar.setBounds(530, 570, 200, 50);

        bGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bGuardar.png"))); // NOI18N
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(bGuardar);
        bGuardar.setBounds(770, 570, 200, 50);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(469, 20, 910, 500);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(220, 130, 210, 30);

        bActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bActualizar.png"))); // NOI18N
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(bActualizar);
        bActualizar.setBounds(290, 570, 200, 50);
        getContentPane().add(txtApellido);
        txtApellido.setBounds(220, 182, 210, 30);
        getContentPane().add(txtDni);
        txtDni.setBounds(220, 80, 210, 30);

        comboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        getContentPane().add(comboGenero);
        comboGenero.setBounds(220, 232, 210, 30);

        comboCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fabrica", "Venta", "Courier", "Admin" }));
        comboCargo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(comboCargo);
        comboCargo.setBounds(220, 432, 210, 30);

        dateNacimiento.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(dateNacimiento);
        dateNacimiento.setBounds(220, 282, 210, 30);

        dateContratacion.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(dateContratacion);
        dateContratacion.setBounds(220, 332, 210, 30);

        dateDespido.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(dateDespido);
        dateDespido.setBounds(220, 492, 210, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Gestionar_Empleados.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1400, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeleccionarActionPerformed
        txtDni.setText(tabla.getValueAt(tabla.getSelectedRow(), 0).toString());
        txtNombre.setText(tabla.getValueAt(tabla.getSelectedRow(), 1).toString());
        txtApellido.setText(tabla.getValueAt(tabla.getSelectedRow(), 2).toString());
        comboGenero.setSelectedItem(tabla.getValueAt(tabla.getSelectedRow(), 3).toString());
        dateNacimiento.setDate(cEmpleados.findEmpleados((Integer) modelo.getValueAt(tabla.getSelectedRow(), 0)).getEmpFechaNacimiento());
        dateContratacion.setDate(cEmpleados.findEmpleados((Integer) modelo.getValueAt(tabla.getSelectedRow(), 0)).getEmpFechaContratacion());
        txtSalario.setText(tabla.getValueAt(tabla.getSelectedRow(), 6).toString());
        comboCargo.setSelectedItem(tabla.getValueAt(tabla.getSelectedRow(), 7).toString());
        dateDespido.setDate(cEmpleados.findEmpleados((Integer) modelo.getValueAt(tabla.getSelectedRow(), 0)).getEmpFechaDespido());
        
        cEdit = cEmpleados.findEmpleados((Integer) modelo.getValueAt(tabla.getSelectedRow(), 0));
    }//GEN-LAST:event_bSeleccionarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        admin_gestionar ventana = new admin_gestionar();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        try {
            Empleados c = new Empleados();

            c.setEmpDni(Integer.parseInt(txtDni.getText()));
            c.setEmpNombre(txtNombre.getText());
            c.setEmpApellido(txtApellido.getText());
            
            String generoS = (String) comboGenero.getSelectedItem();
            char genero = generoS.charAt(0);
            c.setEmpGenero(genero);
            
          //  Date date1=new SimpleDateFormat("dd/MM/yyyy").parse(txtFN.getText()); 
            c.setEmpFechaNacimiento(dateNacimiento.getDate());
            
          //  Date date2=new SimpleDateFormat("dd/MM/yyyy").parse(txtFC.getText()); 
            c.setEmpFechaContratacion(dateContratacion.getDate());
            
            c.setEmpSalario(Integer.parseInt(txtSalario.getText()));
            c.setEmpCargo((String) comboCargo.getSelectedItem());
            
          //  Date date3=new SimpleDateFormat("dd/MM/yyyy").parse(txtFD.getText()); 
            c.setEmpFechaDespido(null);           

            cEmpleados.create(c);
            System.out.println("Los datos fueron guardados");

            CrearModelo();
            Cargar_Informacion();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("Problema el guardar datos");
        }
        
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        try{
            cEdit.setEmpNombre(txtNombre.getText());
            cEdit.setEmpApellido(txtApellido.getText());
            
            String generoS = (String) comboGenero.getSelectedItem();
            char genero = generoS.charAt(0);
            cEdit.setEmpGenero(genero);

            cEdit.setEmpFechaNacimiento(dateNacimiento.getDate());
            cEdit.setEmpFechaContratacion(dateContratacion.getDate());           
            cEdit.setEmpSalario(Integer.parseInt(txtSalario.getText()));           
            cEdit.setEmpCargo((String) comboCargo.getSelectedItem());
            cEdit.setEmpFechaDespido(dateDespido.getDate());           

            cEmpleados.edit(cEdit);
            System.out.println("Se actualizo");
            CrearModelo();
            Cargar_Informacion();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.toString() + "error");
            System.out.println("Error al actualizar");
        }   
    }//GEN-LAST:event_bActualizarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    DefaultTableModel modelo;
    private void CrearModelo() {
        try {
            modelo = (new DefaultTableModel(
                    null, new String[]{
                        "Dni", "Nombres", "Apellidos",
                        "Genero", "F. Nacimiento", "F. Contratacion",
                        "Salario", "Cargo", "F. Despido"}) {
                Class[] types = new Class[]{
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class
                };
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, false, false
                };

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return canEdit[colIndex];
                }
            });
            tabla.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error");
            System.out.println("Problema con el modelo de tabla");
        }
    }
    
    
    private void Cargar_Informacion(){
        try{
            Object o[]=null;
            List<Empleados> listE = cEmpleados.findEmpleadosEntities();
            
            for (int i=0; i< listE.size(); i++){
                modelo.addRow(o);
                modelo.setValueAt(listE.get(i).getEmpDni(), i, 0);
                modelo.setValueAt(listE.get(i).getEmpNombre(), i, 1);
                modelo.setValueAt(listE.get(i).getEmpApellido(), i, 2);
                modelo.setValueAt(listE.get(i).getEmpGenero(), i, 3);
                modelo.setValueAt(darFormato(listE.get(i).getEmpFechaNacimiento()), i, 4);
                modelo.setValueAt(darFormato(listE.get(i).getEmpFechaContratacion()), i, 5);
                modelo.setValueAt(listE.get(i).getEmpSalario(), i, 6);
                modelo.setValueAt(listE.get(i).getEmpCargo(), i, 7);
                modelo.setValueAt(darFormato(listE.get(i).getEmpFechaDespido()), i, 8);
                
            }                                            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("problema al cargar datos");
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_gestionar_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_gestionar_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_gestionar_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_gestionar_empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_gestionar_empleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bSeleccionar;
    private javax.swing.JComboBox<String> comboCargo;
    private javax.swing.JComboBox<String> comboGenero;
    private com.toedter.calendar.JDateChooser dateContratacion;
    private com.toedter.calendar.JDateChooser dateDespido;
    private com.toedter.calendar.JDateChooser dateNacimiento;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
