/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.admin;

import java.awt.Dimension;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Clientes;
import persistencia.ClientesJpaController;
import persistencia.EmpleadosJpaController;

/**
 *
 * @author Kings
 */
public class admin_gestionar_clientes extends javax.swing.JFrame {

    ClientesJpaController cClientes = new ClientesJpaController();
    Clientes cEdit;
    
    /**
     * Creates new form admin_gestionar_clientes
     */
    public admin_gestionar_clientes() {
        initComponents();
        this.setMinimumSize(new Dimension(1400, 680));
        this.setLocationRelativeTo(null);
        CrearModelo();
        Cargar_Informacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSeleccionar = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        txtNIT = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txtDescuento = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        bActualizar = new javax.swing.JButton();
        txtTelefono = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        bCancelar = new javax.swing.JButton();
        txtDireccion = new javax.swing.JTextField();
        comboTipo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        bSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bSeleccionar.png"))); // NOI18N
        bSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSeleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(bSeleccionar);
        bSeleccionar.setBounds(290, 500, 200, 50);

        bGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bGuardar.png"))); // NOI18N
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(bGuardar);
        bGuardar.setBounds(290, 570, 200, 50);

        txtNIT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNITActionPerformed(evt);
            }
        });
        getContentPane().add(txtNIT);
        txtNIT.setBounds(250, 80, 240, 30);

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtEmail);
        txtEmail.setBounds(250, 330, 240, 30);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(570, 20, 800, 600);

        txtDescuento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescuento);
        txtDescuento.setBounds(250, 440, 240, 30);

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtNombre);
        txtNombre.setBounds(250, 130, 240, 30);

        bActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bActualizar.png"))); // NOI18N
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(bActualizar);
        bActualizar.setBounds(50, 500, 200, 50);

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(250, 230, 240, 30);

        txtApellido.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtApellido);
        txtApellido.setBounds(250, 180, 240, 30);

        bCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/bCancelar0.png"))); // NOI18N
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(bCancelar);
        bCancelar.setBounds(50, 570, 200, 50);

        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(250, 280, 240, 30);

        comboTipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hogar", "Empresa", "Constructor" }));
        getContentPane().add(comboTipo);
        comboTipo.setBounds(250, 380, 240, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/Gestionar_Clientes.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 1400, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSeleccionarActionPerformed
        txtNIT.setText(tabla.getValueAt(tabla.getSelectedRow(), 0).toString());
        txtNombre.setText(tabla.getValueAt(tabla.getSelectedRow(), 1).toString());
        txtApellido.setText(tabla.getValueAt(tabla.getSelectedRow(), 2).toString());
        txtTelefono.setText(tabla.getValueAt(tabla.getSelectedRow(), 3).toString());
        txtDireccion.setText(tabla.getValueAt(tabla.getSelectedRow(), 4).toString());
        txtEmail.setText(tabla.getValueAt(tabla.getSelectedRow(), 5).toString());
        comboTipo.setSelectedItem(tabla.getValueAt(tabla.getSelectedRow(), 6).toString());
        txtDescuento.setText(tabla.getValueAt(tabla.getSelectedRow(), 7).toString());

        cEdit = cClientes.findClientes((String) modelo.getValueAt(tabla.getSelectedRow(), 0));
        
    }//GEN-LAST:event_bSeleccionarActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        try {
            Clientes c = new Clientes();

            c.setCliNIT(txtNIT.getText());
            c.setCliNombre(txtNombre.getText());
            c.setCliApellido(txtApellido.getText());
            c.setCliTelefono(txtTelefono.getText());
            c.setCliDireccion(txtDireccion.getText());
            c.setCliEmail(txtEmail.getText());
            c.setCliTipoCliente((String) comboTipo.getSelectedItem());
            c.setCliDescuento(Integer.parseInt(txtDescuento.getText()));

            cClientes.create(c);
            System.out.println("Los datos fueron guardados");

            CrearModelo();
            Cargar_Informacion();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("Problema el guardar datos");
        }
        
    }//GEN-LAST:event_bGuardarActionPerformed

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        try{
            cEdit.setCliNombre(txtNombre.getText());
            cEdit.setCliApellido(txtApellido.getText());
            cEdit.setCliTelefono(txtTelefono.getText());
            cEdit.setCliDireccion(txtDireccion.getText());
            cEdit.setCliEmail(txtEmail.getText());
            cEdit.setCliTipoCliente((String) comboTipo.getSelectedItem());
            cEdit.setCliDescuento(Integer.parseInt(txtDescuento.getText()));

            cClientes.edit(cEdit);
            System.out.println("Se actualizo");
            CrearModelo();
            Cargar_Informacion();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e.toString() + "error");
            System.out.println("Error al actualizar");
        }
        
    }//GEN-LAST:event_bActualizarActionPerformed

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        admin_gestionar ventana = new admin_gestionar();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bCancelarActionPerformed

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoActionPerformed

    private void txtNITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNITActionPerformed

    DefaultTableModel modelo;
    private void CrearModelo() {
        try {
            modelo = (new DefaultTableModel(
                    null, new String[]{
                        "NIT", "Nombres", "Apellidos",
                        "Telefono", "Direccion", "Email",
                        "Tipo", "Descuento"}) {
                Class[] types = new Class[]{
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class,
                    java.lang.String.class
                };
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, false
                };

                @Override
                public Class getColumnClass(int columnIndex) {
                    return types[columnIndex];
                }

                @Override
                public boolean isCellEditable(int rowIndex, int colIndex) {
                    return canEdit[colIndex];
                }
            });
            tabla.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error");
            System.out.println("Problema con el modelo de tabla");
        }
    }
    
    
    private void Cargar_Informacion(){
        try{
            Object o[]=null;
            List<Clientes> listE = cClientes.findClientesEntities();
            
            for (int i=0; i< listE.size(); i++){
                modelo.addRow(o);
                modelo.setValueAt(listE.get(i).getCliNIT(), i, 0);
                modelo.setValueAt(listE.get(i).getCliNombre(), i, 1);
                modelo.setValueAt(listE.get(i).getCliApellido(), i, 2);
                modelo.setValueAt(listE.get(i).getCliTelefono(), i, 3);
                modelo.setValueAt(listE.get(i).getCliDireccion(), i, 4);
                modelo.setValueAt(listE.get(i).getCliEmail(), i, 5);
                modelo.setValueAt(listE.get(i).getCliTipoCliente(), i, 6);
                modelo.setValueAt(listE.get(i).getCliDescuento(), i, 7);
                
            }                                            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
            System.out.println("problema al cargar datos");
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_gestionar_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_gestionar_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_gestionar_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_gestionar_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_gestionar_clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bSeleccionar;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNIT;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
