/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.admin;

import vista.Inicio;

/**
 *
 * @author Kings
 */
public class admin_gestionar extends javax.swing.JFrame {

    /**
     * Creates new form admin_gestionar
     */
    public admin_gestionar() {
        initComponents();
        this.setLocationRelativeTo(null);
       // this.setResizable(false);
       // this.setTitle("Gestionar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bInicio = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        bCliente = new javax.swing.JButton();
        bProveedor = new javax.swing.JButton();
        bEmpleado = new javax.swing.JButton();
        bProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bMateriaP = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bInicio.setText("Inicio");
        bInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInicioActionPerformed(evt);
            }
        });

        jButton2.setText("Gestionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        bCliente.setText("Cliente");
        bCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClienteActionPerformed(evt);
            }
        });

        bProveedor.setText("Proveedor");
        bProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProveedorActionPerformed(evt);
            }
        });

        bEmpleado.setText("Empleado");
        bEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEmpleadoActionPerformed(evt);
            }
        });

        bProducto.setText("Producto");
        bProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProductoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Gestionar: ");

        bMateriaP.setText("Materia P.");
        bMateriaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMateriaPActionPerformed(evt);
            }
        });

        jButton1.setText("Observaciones");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/img/barra.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(650, 650, 650)
                .addComponent(bEmpleado))
            .addGroup(layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(bProducto))
            .addGroup(layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(bMateriaP))
            .addGroup(layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(bCliente))
            .addGroup(layout.createSequentialGroup()
                .addGap(490, 490, 490)
                .addComponent(bProveedor))
            .addComponent(bInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(bEmpleado)
                .addGap(65, 65, 65)
                .addComponent(bProducto))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(bMateriaP))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(bCliente))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(bProveedor))
            .addComponent(bInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProductoActionPerformed
        admin_gestionar_producto ventana = new admin_gestionar_producto();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bProductoActionPerformed

    private void bInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInicioActionPerformed
        Inicio ventana = new Inicio();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bInicioActionPerformed

    private void bClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClienteActionPerformed
       admin_gestionar_clientes ventana = new admin_gestionar_clientes();
       ventana.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_bClienteActionPerformed

    private void bProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProveedorActionPerformed
       admin_gestionar_proveedor ventana = new admin_gestionar_proveedor();
       ventana.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_bProveedorActionPerformed

    private void bEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEmpleadoActionPerformed
       admin_gestionar_empleados ventana = new admin_gestionar_empleados();
       ventana.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_bEmpleadoActionPerformed

    private void bMateriaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMateriaPActionPerformed
       admin_gestionar_materiasPrimas ventana = new admin_gestionar_materiasPrimas();
       ventana.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_bMateriaPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_gestionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_gestionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_gestionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_gestionar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_gestionar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCliente;
    private javax.swing.JButton bEmpleado;
    private javax.swing.JButton bInicio;
    private javax.swing.JButton bMateriaP;
    private javax.swing.JButton bProducto;
    private javax.swing.JButton bProveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
